routes/web.php
<?php

Route::feeds();

// Home
Route::get('/', 'HomeController@show')->name('home');
Route::get('rules', 'HomeController@rules')->name('rules');
Route::get('about', 'HomeController@about')->name('about');
Route::get('terms', 'HomeController@terms')->name('terms');
Route::get('privacy', 'HomeController@privacy')->name('privacy');
// Route::get('bin/{paste?}', 'HomeController@pastebin');

// Authentication
Route::namespace('Auth')->group(function () {
    // Sessions
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login.post');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register')->name('register.post');

    // Password reset
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.forgot');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.forgot.post');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset.post');

    // Email address confirmation
    Route::get('email-confirmation', 'EmailConfirmationController@send')->name('email.send_confirmation');
    Route::get('email-confirmation/{email_address}/{code}', 'EmailConfirmationController@confirm')
        ->name('email.confirm');

    // Social authentication
    Route::get('login/github', 'GithubController@redirectToProvider')->name('login.github');
    Route::get('auth/github', 'GithubController@handleProviderCallback');

    Route::get('login/twitter', 'TwitterController@redirectToProvider')->name('login.twitter');
    Route::get('auth/twitter', 'TwitterController@handleProviderCallback');

    Route::get('login/google', 'GoogleController@redirectToProvider')->name('login.google');
    Route::get('auth/google', 'GoogleController@handleProviderCallback');

    Route::get('login/facebook', 'FacebookController@redirectToProvider')->name('login.facebook');
    Route::get('auth/facebook', 'FacebookController@handleProviderCallback');

});

// Users
Route::get('dashboard', 'DashboardController@show')->name('dashboard');
Route::get('user/{username}', 'ProfileController@show')->name('profile');
Route::get('avatar/{username}', 'ProfileController@avatar')->name('avatar');

// Settings
Route::get('settings', 'Settings\ProfileController@edit')->name('settings.profile');
Route::put('settings', 'Settings\ProfileController@update')->name('settings.profile.update');
Route::delete('settings', 'Settings\ProfileController@destroy')->name('settings.profile.delete');
Route::get('settings/password', 'Settings\PasswordController@edit')->name('settings.password');
Route::put('settings/password', 'Settings\PasswordController@update')->name('settings.password.update');

// Forum
// Route::get('/petitions', 'Forum\ThreadsController@overview')->name('petitions');
Route::prefix('petition')->namespace('Forum')->group(function () {
    Route::get('/', 'ThreadsController@overview')->name('forum');
    Route::get('create-thread', 'ThreadsController@create')->name('threads.create');
    Route::post('create-thread', 'ThreadsController@store')->name('threads.store');

    Route::get('{thread}', 'ThreadsController@show')->name('thread');
    Route::get('{thread}/edit', 'ThreadsController@edit')->name('threads.edit');
    Route::put('{thread}', 'ThreadsController@update')->name('threads.update');
    Route::delete('{thread}', 'ThreadsController@delete')->name('threads.delete');
    Route::put('{thread}/mark-solution/{reply}', 'ThreadsController@markSolution')->name('threads.solution.mark');
    Route::put('{thread}/unmark-solution', 'ThreadsController@unmarkSolution')->name('threads.solution.unmark');
    Route::get('{thread}/subscribe', 'ThreadsController@subscribe')->name('threads.subscribe');
    Route::get('{thread}/unsubscribe', 'ThreadsController@unsubscribe')->name('threads.unsubscribe');

    Route::get('tags/{tag}', 'TagsController@show')->name('forum.tag');
});

// Replies
Route::post('replies', 'ReplyController@store')->name('replies.store');
Route::get('replies/{reply}/edit', 'ReplyController@edit')->name('replies.edit');
Route::put('replies/{reply}', 'ReplyController@update')->name('replies.update');
Route::delete('replies/{reply}', 'ReplyController@delete')->name('replies.delete');

// Subscriptions
Route::get('subscriptions/{subscription}/unsubscribe', 'SubscriptionController@unsubscribe')
    ->name('subscriptions.unsubscribe');

// Admin
Route::prefix('admin')->name('admin')->namespace('Admin')->group(function () {
    Route::get('/', 'AdminController@index');
    Route::get('users/{username}', 'UsersController@show')->name('.users.show');
    Route::put('users/{username}/ban', 'UsersController@ban')->name('.users.ban');
    Route::put('users/{username}/unban', 'UsersController@unban')->name('.users.unban');
    Route::delete('users/{username}', 'UsersController@delete')->name('.users.delete');
});

app/Models/Thread.php
<?php

namespace App\Models;

use App\Exceptions\CouldNotMarkReplyAsSolution;
use App\Helpers\HasAuthor;
use App\Helpers\HasLikes;
use App\Helpers\HasSlug;
use App\Helpers\HasTags;
use App\Helpers\HasTimestamps;
use App\Helpers\ModelHelpers;
use App\Helpers\ProvidesSubscriptions;
use App\Helpers\ReceivesReplies;
use DB;
use Exception;
use Illuminate\Contracts\Pagination\Paginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection as SupportCollection;
use Illuminate\Support\Str;
use Spatie\Feed\Feedable;
use Spatie\Feed\FeedItem;

final class Thread extends Model implements ReplyAble, SubscriptionAble, Feedable
{
    use HasAuthor;
    use HasLikes;
    use HasSlug;
    use HasTags;
    use HasTimestamps;
    use ModelHelpers;
    use ProvidesSubscriptions;
    use ReceivesReplies;

    const TABLE = 'threads';

    const FEED_PAGE_SIZE = 20;

    /**
     * {@inheritdoc}
     */
    protected $table = self::TABLE;

    /**
     * {@inheritdoc}
     */
    protected $fillable = [
        'body',
        'slug',
        'subject',
    ];

    public function id(): int
    {
        return $this->id;
    }

    public function subject(): string
    {
        return $this->subject;
    }

    public function body(): string
    {
        return $this->body;
    }

    public function excerpt(int $limit = 100): string
    {
        return Str::limit(strip_tags(md_to_html($this->body())), $limit);
    }

    public function solutionReply(): ?Reply
    {
        return $this->solutionReplyRelation;
    }

    public function solutionReplyRelation(): BelongsTo
    {
        return $this->belongsTo(Reply::class, 'solution_reply_id');
    }

    public function isSolved(): bool
    {
        return ! is_null($this->solution_reply_id);
    }

    public function isSolutionReply(Reply $reply): bool
    {
        if ($solution = $this->solutionReply()) {
            return $solution->matches($reply);
        }

        return false;
    }

    public function markSolution(Reply $reply)
    {
        $thread = $reply->replyAble();

        if (! $thread instanceof self) {
            throw CouldNotMarkReplyAsSolution::replyAbleIsNotAThread($reply);
        }

        $this->solutionReplyRelation()->associate($reply);
        $this->save();
    }

    public function unmarkSolution()
    {
        $this->solutionReplyRelation()->dissociate();
        $this->save();
    }

    public function delete()
    {
        $this->removeTags();
        $this->deleteReplies();

        parent::delete();
    }

    public function toFeedItem(): FeedItem
    {
        $updatedAt = Carbon::parse($this->latest_creation);

        return FeedItem::create()
            ->id($this->id)
            ->title($this->subject)
            ->summary($this->body)
            ->updated($updatedAt)
            ->link(route('thread', $this->slug))
            ->author($this->author()->name);
    }

    /**
     * @return \App\Models\Thread[]
     */
    public static function feed(int $limit = 20): Collection
    {
        return static::feedQuery()->limit($limit)->get();
    }

    /**
     * @return \App\Models\Thread[]
     */
    public static function feedPaginated(int $perPage = 20): Paginator
    {
        return static::feedQuery()->paginate($perPage);
    }

    /**
     * @return \App\Models\Thread[]
     */
    public static function feedByTagPaginated(Tag $tag, int $perPage = 20): Paginator
    {
        return static::feedQuery()
            ->join('taggables', function ($join) use ($tag) {
                $join->on('threads.id', 'taggables.taggable_id')
                    ->where('taggable_type', static::TABLE);
            })
            ->where('taggables.tag_id', $tag->id())
            ->paginate($perPage);
    }

    /**
     * This will order the threads by creation date and latest reply.
     */
    public static function feedQuery(): Builder
    {
        return static::with('solutionReplyRelation')
            ->leftJoin('replies', function ($join) {
                $join->on('threads.id', 'replies.replyable_id')
                    ->where('replies.replyable_type', static::TABLE);
            })
            ->orderBy('latest_creation', 'DESC')
            ->groupBy('threads.id')
            ->select('threads.*', DB::raw('
                CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at
                THEN COALESCE(MAX(replies.created_at), 0)
                ELSE threads.created_at
                END AS latest_creation
            '));
    }

    /**
     * This will calculate the average resolution time in days of all threads marked as resolved.
     */
    public static function resolutionTime()
    {
        try {
            return static::join('replies', 'threads.solution_reply_id', '=', 'replies.id')
                ->select(DB::raw('avg(datediff(replies.created_at, threads.created_at)) as duration'))
                ->pluck('duration')
                ->first();
        } catch (Exception $e) {
            return false;
        }
    }

    public static function getFeedItems(): SupportCollection
    {
        return static::feedQuery()
            ->paginate(static::FEED_PAGE_SIZE)
            ->getCollection();
    }
}

app/Http/Controllers/Forum/TagsController.php
<?php

namespace App\Http\Controllers\Forum;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use App\Models\Thread;

class TagsController extends Controller
{
    public function show(Tag $tag)
    {
        return view('forum.overview', ['threads' => Thread::feedByTagPaginated($tag), 'activeTag' => $tag]);
    }
}

app/Http/Controllers/Forum/ThreadsController.php
<?php

namespace App\Http\Controllers\Forum;

use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfUnconfirmed;
use App\Http\Requests\ThreadRequest;
use App\Jobs\CreateThread;
use App\Jobs\DeleteThread;
use App\Jobs\MarkThreadSolution;
use App\Jobs\SubscribeToSubscriptionAble;
use App\Jobs\UnmarkThreadSolution;
use App\Jobs\UnsubscribeFromSubscriptionAble;
use App\Jobs\UpdateThread;
use App\Models\Reply;
use App\Models\Tag;
use App\Models\Thread;
use App\Policies\ThreadPolicy;
use App\Queries\SearchThreads;
use Illuminate\Auth\Middleware\Authenticate;
use Illuminate\Http\Request;

class ThreadsController extends Controller
{
    public function __construct()
    {
        $this->middleware([Authenticate::class, RedirectIfUnconfirmed::class], ['except' => ['overview', 'show']]);
    }

    public function overview()
    {
        $search = request('search');
        $threads = $search ? SearchThreads::get($search) : Thread::feedPaginated();

        return view('forum.overview', compact('threads', 'search'));
    }

    public function show(Thread $thread)
    {
        return view('forum.threads.show', compact('thread'));
    }

    public function create()
    {
        $tags = Tag::all()->map(function ($tag) {
            return ['name' => $tag->name, 'id' => $tag->id];
        });

        $selectedTags = collect(old('tags'))->map(function ($selected) use ($tags) {
            return $tags->where('id', $selected)->first();
        });

        return view('forum.threads.create', ['tags' => $tags, 'selectedTags' => $selectedTags]);
    }

    public function store(ThreadRequest $request)
    {
        $thread = $this->dispatchNow(CreateThread::fromRequest($request));

        $this->success('forum.threads.created');

        return redirect()->route('thread', $thread->slug());
    }

    public function edit(Thread $thread)
    {
        $this->authorize(ThreadPolicy::UPDATE, $thread);
        $selectedTags = $thread->tags()->map(function ($tag) {
            return ['name' => $tag->name, 'id' => $tag->id];
        });

        return view('forum.threads.edit', ['thread' => $thread, 'tags' => Tag::all(), 'selectedTags' => $selectedTags]);
    }

    public function update(ThreadRequest $request, Thread $thread)
    {
        $this->authorize(ThreadPolicy::UPDATE, $thread);

        $thread = $this->dispatchNow(UpdateThread::fromRequest($thread, $request));

        $this->success('forum.threads.updated');

        return redirect()->route('thread', $thread->slug());
    }

    public function delete(Thread $thread)
    {
        $this->authorize(ThreadPolicy::DELETE, $thread);

        $this->dispatchNow(new DeleteThread($thread));

        $this->success('forum.threads.deleted');

        return redirect()->route('forum');
    }

    public function markSolution(Thread $thread, Reply $reply)
    {
        $this->authorize(ThreadPolicy::UPDATE, $thread);

        $this->dispatchNow(new MarkThreadSolution($thread, $reply));

        return redirect()->route('thread', $thread->slug());
    }

    public function unmarkSolution(Thread $thread)
    {
        $this->authorize(ThreadPolicy::UPDATE, $thread);

        $this->dispatchNow(new UnmarkThreadSolution($thread));

        return redirect()->route('thread', $thread->slug());
    }

    public function subscribe(Request $request, Thread $thread)
    {
        $this->authorize(ThreadPolicy::SUBSCRIBE, $thread);

        $this->dispatchNow(new SubscribeToSubscriptionAble($request->user(), $thread));

        $this->success("You're now subscribed to this thread.");

        return redirect()->route('thread', $thread->slug());
    }

    public function unsubscribe(Request $request, Thread $thread)
    {
        $this->authorize(ThreadPolicy::UNSUBSCRIBE, $thread);

        $this->dispatchNow(new UnsubscribeFromSubscriptionAble($request->user(), $thread));

        $this->success("You're now unsubscribed from this thread.");

        return redirect()->route('thread', $thread->slug());
    }
}

app/Http/Livewire/LikeReply.php
<?php

namespace App\Http\Livewire;

use App\Jobs\LikeReply as LikeReplyJob;
use App\Jobs\UnlikeReply as UnlikeReplyJob;
use App\Models\Reply;
use App\User;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class LikeReply extends Component
{
    use DispatchesJobs;

    public $likes;

    public $replyId;

    public function mount(Reply $reply): void
    {
        $this->replyId = $reply->id;
        $this->likes = $this->reply->likes_count;
    }

    public function getReplyProperty(): Reply
    {
        return Reply::findOrFail($this->replyId);
    }

    public function getUserProperty(): ?User
    {
        return Auth::user();
    }

    public function toggleLike(): void
    {
        if (! $this->user) {
            return;
        }

        if ($this->reply->isLikedBy($this->user)) {
            $this->dispatchNow(new UnlikeReplyJob($this->reply, $this->user));
        } else {
            $this->dispatchNow(new LikeReplyJob($this->reply, $this->user));
        }

        $this->likes = $this->reply->likes_count;
    }
}

app/Http/Livewire/LikeThread.php
<?php

namespace App\Http\Livewire;

use App\Jobs\LikeThread as LikeThreadJob;
use App\Jobs\UnlikeThread as UnlikeThreadJob;
use App\Models\Thread;
use App\User;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class LikeThread extends Component
{
    use DispatchesJobs;

    public $likes;

    public $threadId;

    public function mount(Thread $thread): void
    {
        $this->threadId = $thread->id;
        $this->likes = $this->thread->likes_count;
    }

    public function getThreadProperty(): Thread
    {
        return Thread::findOrFail($this->threadId);
    }

    public function getUserProperty(): ?User
    {
        return Auth::user();
    }

    public function toggleLike(): void
    {
        if (! $this->user) {
            return;
        }

        if ($this->thread->isLikedBy($this->user)) {
            $this->dispatchNow(new UnlikeThreadJob($this->thread, $this->user));
        } else {
            $this->dispatchNow(new LikeThreadJob($this->thread, $this->user));
        }

        $this->likes = $this->thread->likes_count;
    }
}

resources/views/forum/threads/_form.blade.php
<form action="{{ route(...$route) }}" method="POST">
    @csrf
    @method($method ?? 'POST')


    @formGroup('subject')
        <label for="subject">Subject</label>
        <input type="text" name="subject" id="subject" value="{{ isset($thread) ? $thread->subject() : null }}" class="form-control" required maxlength="60" />
        <span class="text-gray-600 text-sm">Maximum 60 characters.</span>
        @error('subject')
    @endFormGroup

    @formGroup('body')
        <label for="body">Body</label>
        <editor
            name="body"
            id="body"
            content="{{ old('body') ?: isset($thread) ? $thread->body() : null }}"
        ></editor>
        @error('body')
    @endFormGroup

    @formGroup('tags')
        <label for="tags">Tags</label>
        <multi-select 
            :initial-value="{{ $selectedTags ?? '[]' }}"
e           :options="{{ $tags }}" 
            :max="3"
            placeholder="Choose up to 3 tags" 
            label="name" 
            track-by="name"
            name="tags[]"
            identifier="create-thread">
            @php($selected = isset($thread) ? $thread->tags()->pluck('id')->toArray() : [])
            <select name="tags[]" id="create-thread" class="hidden" multiple>
                @foreach($tags->toArray() as $tag)
                    <option value="{{ $tag['id'] }}" @if(in_array($tag['id'], $selected)) selected @endif>{{ $tag['name'] }}</option>
                @endforeach
            </select>
        </multi-select>
        @error('tags')
    @endFormGroup

    <div class="flex justify-end items-center">
        <a href="{{ isset($thread) ? route('thread', $thread->slug()) : route('forum') }}" class="text-green-darker mr-4">Cancel</a>
        <button type="submit" class="button button-primary">{{ isset($thread) ? 'Update Petition' : 'Start a petition' }}</button>
    </div>
</form>

resources/views/forum/threads/show.blade.php
@title($thread->subject())

@extends('layouts.default')

@section('content')
    <div class="bg-white border-b">
        <div class="container mx-auto flex justify-between items-center px-4">
            <h1 class="text-xl py-4 text-gray-900">
                <a href="{{ route('forum') }}">Petitions</a>
                > {{ $title }}
            </h1>
            
            <form action="{{ route('forum') }}" method="GET">
                <input type="text" name="search" id="search" value="{{ $search ?? null }}" class="rounded border-2 border-gray-300 py-1 px-3 focus:outline-none focus:border-blue-900" placeholder="Search for petitions..." />
            </form>
        </div>
    </div>
    <div class="container mx-auto px-4 pt-4">
        <div class="flex flex-wrap">
            <div class="w-full md:w-3/4 md:pr-3">
                <div class="reply bg-white border rounded">
                    <div class="flex flex-col md:flex-row md:items-center text-sm p-4 border-b">
                        <div class="flex mb-4 md:mb-0">
                            @include('forum.threads.info.avatar', ['user' => $thread->author()])

                            <div class="mr-6 text-gray-700">
                                <a href="{{ route('profile', $thread->author()->username()) }}" class="text-green-darker mr-2">{{ $thread->author()->name() }}</a> posted
                                {{ $thread->createdAt()->diffForHumans() }}
                            </div>
                        </div>

                        @include('forum.threads.info.tags')
                    </div>
                    <div class="p-4">
                        <reply :content="{{ json_encode(md_to_html($thread->body())) }}"/>
                    </div>
                    <div class="border-t">
                        @livewire('like-thread', $thread)
                    </div>
                </div>

                @foreach ($thread->replies() as $reply)
                    <div class="reply mt-8 bg-white rounded {{ $thread->isSolutionReply($reply) ? 'border-2 border-green-primary' : 'border' }}" id="{{ $reply->id }}">
                        
                        @if ($thread->isSolutionReply($reply))
                            <div class="bg-green-primary text-white uppercase px-4 py-2 opacity-75">
                                Solution
                            </div>
                        @endif

                        <div>
                            <div class="flex flex-col md:flex-row md:items-center text-sm p-4 border-b">
                                <div class="flex flex-wrap mb-4 md:mb-0 justify-between w-full items-center">
                                    <div class="flex">
                                        @include('forum.threads.info.avatar', ['user' => $reply->author()])

                                        <div class="mr-6 mb-4 md:mb-0 text-gray-700">
                                            <a href="{{ route('profile', $reply->author()->username()) }}" class="text-green-darker">
                                                {{ $reply->author()->name() }}
                                            </a> replied
                                            {{ $reply->createdAt()->diffForHumans() }}
                                        </div>
                                    </div>
                                    <div class="flex reply-options">

                                        @can(App\Policies\ReplyPolicy::UPDATE, $reply)
                                            <a class="label label-primary" href="{{ route('replies.edit', $reply->id()) }}">
                                                Edit
                                            </a>
                                            <a href="#" @click.prevent="activeModal = 'delete-reply-{{ $reply->id }}'" class="label label-danger">
                                                Delete
                                            </a>
                                        @endcan

                                        @can(App\Policies\ThreadPolicy::UPDATE, $thread)
                                
                                            @if ($thread->isSolutionReply($reply))
                                                <a href="#" @click.prevent="activeModal = 'unmark-solution-{{ $thread->id }}'" class="label">
                                                    Unmark As Solution
                                                </a>

                                                @include('_partials._update_modal', [
                                                    'identifier' => "unmark-solution-{$thread->id}",
                                                    'route' => ['threads.solution.unmark', $thread->slug()],
                                                    'title' => 'Unmark As Solution',
                                                    'body' => '<p>Confirm to unmark this reply as the solution for <strong>"'.e($thread->subject()).'"</strong>.</p>',
                                                ])
                                            @else
                                                <a href="#" @click.prevent="activeModal = 'mark-solution-{{ $reply->id }}'" class="label" >
                                                    Mark As Solution
                                                </a>

                                                @include('_partials._update_modal', [
                                                    'identifier' => "mark-solution-{$reply->id}",
                                                    'route' => ['threads.solution.mark', [$thread->slug(), $reply->id()]],
                                                    'title' => 'Mark As Solution',
                                                    'body' => '<p>Confirm to mark this reply as the solution for <strong>"'.e($thread->subject()).'"</strong>.</p>',
                                                ])
                                            @endif
                                            
                                        @endcan
                                    </div>
                                </div>              
                            </div>
                            <div class="p-4">
                                <reply :content="{{ json_encode(md_to_html($reply->body())) }}"/>
                            </div>                            
                            <div class="border-t">
                                @livewire('like-reply', $reply)
                            </div>
                        </div>
                    </div>

                    @include('_partials._delete_modal', [
                        'identifier' => "delete-reply-{$reply->id}",
                        'route' => ['replies.delete', $reply->id()],
                        'title' => 'Delete Comment',
                        'body' => '<p>Are you sure you want to delete this Comment? This cannot be undone.</p>',
                    ])
                @endforeach

                @can(App\Policies\ReplyPolicy::CREATE, App\Models\Reply::class)
                    @if ($thread->isConversationOld())
                        <hr>
                        <p class="text-center">
                            The last reply to this petition was more than six months ago. Please consider <a href="{{ route('threads.create') }}">opening a new petition</a> if you have a similar problem.
                        </p>
                    @else
                        <div class="my-8">

                            <form action="{{ route('replies.store') }}" method="POST">
                                @csrf

                                @formGroup('body')
                                    <label for="body">Write a reply</label>
                                    <editor 
                                        name="body" 
                                        id="body"
                                        content="{{ old('body') }}"
                                    ></editor>
                                    @error('body')
                                @endFormGroup

                                <input type="hidden" name="replyable_id" value="{{ $thread->id() }}" />
                                <input type="hidden" name="replyable_type" value="threads" />

                                <div class="flex justify-between items-center mt-4">
                                    <p class="text-sm text-gray-500 mr-8">
                                        Please make sure you've read our <a href="{{ route('rules') }}" class="text-green-dark">Webiste Rules</a> before commenting to this petition.
                                    </p>

                                    <button type="submit" class="button button-primary">Reply</button>
                                </div>
                            </form>

                        </div>
                    @endif
                @else
                    @if (Auth::guest())
                        <p class="text-center text-gray-800 border-t py-8">
                            <a href="{{ route('login') }}" class="text-green-darker">Sign in</a> to participate in this petition!
                        </p>
                    @else
                        <div class="bg-gray-400 rounded p-4 text-gray-700 my-8">
                            <p>You'll need to verify your account before participating in this petition.</p>
                            <p><a href="{{ route('email.send_confirmation') }}" class="text-green-dark">Click here to resend the verification link.</p>
                        </div>
                    @endif
                @endcan
            </div>  
            <div class="w-full hidden md:w-1/4 md:pl-3 md:pt-4 md:flex items-center flex-col text-center mb-4">
                @include('users._user_info', ['user' => $thread->author(), 'avatarSize' => 100])

                <div class="reply-options">
                @can(App\Policies\ThreadPolicy::UPDATE, $thread)
                    <a class="label" href="{{ route('threads.edit', $thread->slug()) }}">
                        Edit
                    </a>
                @endcan

                @can(App\Policies\ThreadPolicy::UNSUBSCRIBE, $thread)
                    <a class="label" href="{{ route('threads.unsubscribe', $thread->slug()) }}">
                        Unsubscribe
                    </a>
                @elsecan(App\Policies\ThreadPolicy::SUBSCRIBE, $thread)
                    <a class="label" href="{{ route('threads.subscribe', $thread->slug()) }}">
                        Subscribe
                    </a>
                @endcan

                @can(App\Policies\ThreadPolicy::DELETE, $thread)
                    <a class="label label-danger" @click.prevent="activeModal = 'deleteThread'">
                        Delete
                    </a>

                    @include('_partials._delete_modal', [
                        'identifier' => 'deleteThread',
                        'route' => ['threads.delete', $thread->slug()],
                        'title' => 'Delete Petition',
                        'body' => '<p>Are you sure you want to delete this petition and its updates and comments? This cannot be undone.</p>',
                    ])
                @endcan
                </div>

                <div class="w-full">
                    @include('layouts._ads._forum_sidebar')
                </div>
            </div>
        </div>
    </div>
@endsection